CHROME, EDGE, FIREFOX = ('Chrome','Edge','Firefox')
WINDOWS, LINUX, OSX = ('Windows', 'Linux', 'Darwin')
ROOT_PATH = 'bot/'
HEADLESS = None
WEBDRIVER = None
DEV = None
DRY_RUN = None
DRIVER_PATH = 'bot/driver/'
OS = None
APPRISE_CONFIG_PATH = "bot/config/config.yml"
PROCESSES_NUM = None
CAPTCHA = None